server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /auth/ {
        proxy_pass http://backend:4000;
    }

    location /vaccination/ {
        proxy_pass http://backend:4000;
    }

    location /verify/ {
        proxy_pass http://backend:4000;
    }
}
